name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Jerred Shepherd (RiotShielder)
website: http://shepherdjerred.com/

depend: [VaultEconomy]

main: com.shepherdjerred.stranks.Main

commands:
    stranks:
        description: Admin command for stRanks
        aliases: [str]
    rank:
        description: Main command for stRanks
        aliases: [r]

permissions:
    stRanks.rank:
        description: Use /rank
        default: true
    stRanks.list:
        description: Use /rank list
        default: true
    stRanks.info:
        description: Use /rank info
        default: true
    stRanks.buy:
        description: Use /rank buy
        default: true